# -*- coding: utf-8 -*-
"""password checker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14hzRHgztzSfwFjkKt6oY6msb0X04Kyqk
"""

import re
print("Smart Password Strength Checker")
password = input("Enter a password: ")

score = 0
feedback = []

if len(password) >= 8:
  score += 1
else:
  feedback.append("Password should be atleast 8 characters long")

if re.search(r"[A-Z]", password):
  score += 1
else:
  feedback.append("Add at least one uppercase letter")

if re.search(r"[a-z]", password):
  score += 1
else:
  feedback.append("Add at least one lowercase letter")

if re.search(r"[0-9]", password):
  score += 1
else:
  feedback.append("Include at least one number ")

if re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
    score += 1
else:
    feedback.append("Include at least one special character.")

print("Password Strength Result: ")

if score >= 5:
    print("Strong Password ")
elif score >= 3:
    print("Medium Password ")
else:
    print("Weak Password ")

if feedback:
    print("Suggestions to improve your password:")
    for item in feedback:
        print("-", item)